INSERT INTO Students (Name, Age, Major, GPA) VALUES ('Alice', 22, 'Computer Science', 3.8);
INSERT INTO Students (Name, Age, Major, GPA) VALUES ('Bob', 19, 'Mathematics', 3.6);
INSERT INTO Students (Name, Age, Major, GPA) VALUES ('Charlie', 20, 'Physics', 3.5);
INSERT INTO Students (Name, Age, Major, GPA) VALUES ('David', 23, 'Biology', 3.7);
INSERT INTO Students (Name, Age, Major, GPA) VALUES ('Eve', 21, 'Chemistry', 3.4);
INSERT INTO Students (Name, Age, Major, GPA) VALUES ('Frank', 22, 'Engineering', 3.9);
INSERT INTO Students (Name, Age, Major, GPA) VALUES ('Grace', 19, 'Economics', 3.3);
INSERT INTO Students (Name, Age, Major, GPA) VALUES ('Heidi', 20, 'Computer Science', 3.6);
INSERT INTO Students (Name, Age, Major, GPA) VALUES ('Ivan', 23, 'Mathematics', 3.8);
INSERT INTO Students (Name, Age, Major, GPA) VALUES ('Judy', 21, 'Physics', 3.4);
INSERT INTO Students (Name, Age, Major, GPA) VALUES ('Karl', 22, 'Biology', 3.9);
INSERT INTO Students (Name, Age, Major, GPA) VALUES ('Linda', 19, 'Chemistry', 3.3);
INSERT INTO Students (Name, Age, Major, GPA) VALUES ('Mike', 20, 'Engineering', 3.7);
INSERT INTO Students (Name, Age, Major, GPA) VALUES ('Nancy', 23, 'Economics', 3.5);
INSERT INTO Students (Name, Age, Major, GPA) VALUES ('Oliver', 21, 'Computer Science', 3.9);
INSERT INTO Students (Name, Age, Major, GPA) VALUES ('Patricia', 22, 'Mathematics', 3.3);
INSERT INTO Students (Name, Age, Major, GPA) VALUES ('Quentin', 19, 'Physics', 3.8);
INSERT INTO Students (Name, Age, Major, GPA) VALUES ('Rebecca', 20, 'Biology', 3.4);
INSERT INTO Students (Name, Age, Major, GPA) VALUES ('Steve', 23, 'Chemistry', 3.6);
INSERT INTO Students (Name, Age, Major, GPA) VALUES ('Tina', 21, 'Engineering', 3.9);
INSERT INTO Students (Name, Age, Major, GPA) VALUES ('Ursula', 22, 'Economics', 3.3);
INSERT INTO Students (Name, Age, Major, GPA) VALUES ('Victor', 19, 'Computer Science', 3.7);
INSERT INTO Students (Name, Age, Major, GPA) VALUES ('Wendy', 20, 'Mathematics', 3.5);
INSERT INTO Students (Name, Age, Major, GPA) VALUES ('Xavier', 23, 'Physics', 3.9);
INSERT INTO Students (Name, Age, Major, GPA) VALUES ('Yvonne', 21, 'Biology', 3.3);
INSERT INTO Students (Name, Age, Major, GPA) VALUES ('Zachary', 22, 'Chemistry', 3.8);
INSERT INTO Students (Name, Age, Major, GPA) VALUES ('Amelia', 19, 'Engineering', 3.4);
INSERT INTO Students (Name, Age, Major, GPA) VALUES ('Benjamin', 20, 'Economics', 3.6);
INSERT INTO Students (Name, Age, Major, GPA) VALUES ('Clara', 23, 'Computer Science', 3.9);
INSERT INTO Students (Name, Age, Major, GPA) VALUES ('Daniel', 21, 'Mathematics', 3.3);
INSERT INTO Students (Name, Age, Major, GPA) VALUES ('Emily', 22, 'Physics', 3.8);
INSERT INTO Students (Name, Age, Major, GPA) VALUES ('Frederick', 19, 'Biology', 3.4);
INSERT INTO Students (Name, Age, Major, GPA) VALUES ('Gabrielle', 20, 'Chemistry', 3.6);
INSERT INTO Students (Name, Age, Major, GPA) VALUES ('Hannah', 23, 'Engineering', 3.9);
INSERT INTO Students (Name, Age, Major, GPA) VALUES ('Isaac', 21, 'Economics', 3.3);
INSERT INTO Students (Name, Age, Major, GPA) VALUES ('Jacqueline', 22, 'Computer Science', 3.8);
INSERT INTO Students (Name, Age, Major, GPA) VALUES ('Kevin', 19, 'Mathematics', 3.6);
INSERT INTO Students (Name, Age, Major, GPA) VALUES ('Laura', 20, 'Physics', 3.3);
INSERT INTO Students (Name, Age, Major, GPA) VALUES ('Matthew', 23, 'Biology', 3.9);
INSERT INTO Students (Name, Age, Major, GPA) VALUES ('Nicole', 21, 'Chemistry', 3.4);
INSERT INTO Students (Name, Age, Major, GPA) VALUES ('Oscar', 22, 'Engineering', 3.6);
INSERT INTO Students (Name, Age, Major, GPA) VALUES ('Pamela', 19, 'Economics', 3.9);
INSERT INTO Students (Name, Age, Major, GPA) VALUES ('Quincy', 20, 'Computer Science', 3.3);
INSERT INTO Students (Name, Age, Major, GPA) VALUES ('Rachel', 23, 'Mathematics', 3.8);
INSERT INTO Students (Name, Age, Major, GPA) VALUES ('Samuel', 21, 'Physics', 3.4);
INSERT INTO Students (Name, Age, Major, GPA) VALUES ('Theresa', 22, 'Biology', 3.6);
INSERT INTO Students (Name, Age, Major, GPA) VALUES ('Ulysses', 19, 'Chemistry', 3.9);
INSERT INTO Students (Name, Age, Major, GPA) VALUES ('Virginia', 20, 'Engineering', 3.3);
INSERT INTO Students (Name, Age, Major, GPA) VALUES ('Walter', 23, 'Economics', 3.8);
INSERT INTO Students (Name, Age, Major, GPA) VALUES ('Xenia', 21, 'Computer Science', 3.4);
INSERT INTO Students (Name, Age, Major, GPA) VALUES ('York', 22, 'Mathematics', 3.6);
INSERT INTO Students (Name, Age, Major, GPA) VALUES ('Zoe', 19, 'Physics', 3.9);

