@startuml

scale 2

interface Subject {
  + request()
}

class RealSubject {
  + request()
}

class Proxy {
  + request()
  - real_subject: RealSubject
}

Subject <|-down- RealSubject
Subject <|-down- Proxy
Proxy --up> RealSubject

@enduml